CREATE TABLE IF NOT EXISTS public."user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" TEXT,
  "name" TEXT,
  "email" TEXT,
  "phone" TEXT,
  "avatar" TEXT,
  "geo" JSONB default '{}',
  "timezone" TEXT,
  "language" TEXT,
  "password" TEXT,
  "status" SMALLINT DEFAULT 0,
  "register_time" TIMESTAMP DEFAULT now() 
);

insert into public.user (name, email, phone, avatar, geo, language, password) values ('liaoxin', 'lx@gmail.com', '12345678901', '', '{}', 'en', 'xxxxxxx');